spring.application.name=backend
server.port=8081

rate-limiter.algorithm=sliding-window

gateway.target-base-url=http://localhost:8080

rate-limiter.token-bucket.capacity=1
rate-limiter.token-bucket.refill-rate-per-second=1.0

rate-limiter.fixed-window.limit=5
rate-limiter.fixed-window.window-seconds=60

rate-limiter.sliding-window.limit=5
rate-limiter.sliding-window.window-seconds=60

rate-limiter.sliding-window-counter.limit=5
rate-limiter.sliding-window-counter.window-seconds=60

rate-limiter.leaking-bucket.capacity=1
rate-limiter.leaking-bucket.leaking-rate=1
