spring.application.name=backend
server.port=8081

rate-limiter.algorithm=fixed-window

spring.data.redis.host=localhost
spring.data.redis.port=6379

gateway.target-base-url=http://localhost:8080

rate-limiter.token-bucket.capacity=1
rate-limiter.token-bucket.refill-rate-per-second=1.0

rate-limiter.fixed-window.limit=1
rate-limiter.fixed-window.window-seconds=10
